url: "http://www.ipdk.io"
baseurl: ""
title: Infrastructure Programmer Development Kit
title-cn: Infrastructure Programmer Development Kit
email: tbd@intel.com
author: TBD
description: >
  IPDK, or Infrastructure Programmer Development Kit, is an open source, vendor-agnostic framework of drivers and APIs for infrastructure offload and management that runs on a CPU or an IPU.  IPDK runs in Linux and uses a set of well-established tools such as SPDK, DPDK, Quick Assist and P4 to enable network virtualization, storage virtualization, workload provisioning, root-of-trust and offload capabilities found in the platform.  The components within IPDK, already optimized for Xeon servers, provide a common platform across CPUs and IPUs for increasing performance, optimizing resources and securing the infrastructure with an open-source eco-system.
markdown: kramdown
highlighter: rouge
permalink: pretty
include: [.well-known]

boxes:
  - title: documentation
    title-cn: 文档
    url: /documentation/
  - title: development
    title-cn: 开发
    url: /development/
  - title: community
    title-cn: 社区
    url: /community/
  - title: News
    title-cn: 动态
    url: /blog/
  - title: CI Status
    title-cn: 身份
    url: /ci-status/

collections:
  documentation:
    output: true
  development:
    output: true
